# Configuração básica para o Air
dev = true

[build]
# Diretório onde o binário será gerado
bin = "tmp/main"
cmd = "go build -o tmp/main ./cmd/server"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp"]

[log]
level = "debug"

[run]
# Comando para executar o binário gerado
cmd = "tmp/main"
