services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  server:
    build:
      context: .
      dockerfile: .build/dev/Dockerfile.dev
      args:
        API_PORT: ${API_PORT}
        SERVICE_NAME: ${SERVICE_NAME}
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      OTEL_ENABLED: true
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: sub-watch-backend
      OTEL_RESOURCE_ATTRIBUTES: service.version=1.0.0,service.environment=local
    volumes:
      - .:/app
      - /app/tmp
    command: ["air"]
    networks:
      - app_network
      - observability

networks:
  app_network:
    driver: bridge
  observability:
    external: true
    name: subwatch-observability

volumes:
  postgres_data:
  