services:
  server:
    build:
      context: .
      dockerfile: .build/dev/Dockerfile.dev
      args:
        API_PORT: ${API_PORT}
        SERVICE_NAME: ${SERVICE_NAME}
        CNPJ_FINDER_URL: ${CNPJ_FINDER_URL}
        CNPJ_FINDER_TIMEOUT: ${CNPJ_FINDER_TIMEOUT}
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      OTEL_ENABLED: true
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: cnpj-finder
      OTEL_RESOURCE_ATTRIBUTES: service.version=1.0.0,service.environment=local
    volumes:
      - .:/app
      - /app/tmp
    command: ["air"]
    networks:
      - app_network
      - observability

networks:
  app_network:
    driver: bridge
  observability:
    external: true
    name: subwatch-observability
